---
title: "time-series-proj"
author: "Kyler Cheong"
date: "2023-05-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Time Series Project

This project I attempt to do a simple time series analysis of Singapore weather data. I attempt to predict the mean monthly temperature.

```{r read data}
data = read.csv("./data/data.csv")
```

```{r EDA}
# check for null values
colSums(is.na(data))

# plot
#install.packages("ggplot2")
library(ggplot2)
ggplot(data, aes(x = year, y = value, group = level_1, color = level_1)) +
  geom_line() +
  labs(title = "Line Plot of Three Categories", x = "Year", y = "Value", color = 'Type')
```

```{r keep only one column}
# total fertility rate
fertilityRate = subset(data, level_1 == "Total Fertility Rate")
fertilityRate = fertilityRate[, c(1,3)]
plot(x = fertilityRate$year, y = fertilityRate$value, type = "l",
     main = "Total Fertility Rate from 1960 to 2018",
     xlab = "Per Female",
     ylab = "Year")
```
```{r train test split}
train = fertilityRate[c(1:54),]
test = fertilityRate[c(55:59),]
#plot(train_fertilityRate, type = "l")
#plot(test_fertilityRate, type = "l")
```


```{r time series analysis of data1}
# ACF and PACF of raw data
acf(train[, c(2)])
pacf(train[, c(2)])
```

```{r differencing}
# first difference
train_firstDiff = diff(train[, c(2)], difference = 1)
plot(train_firstDiff, type = "l", main = "first difference")

# second difference
# secDiff = diff(train[, c(2)], difference = 2)
# plot(secDiff, type = "l", main = "second difference")
```

```{r differencing of smoothed data}
# log transformation
log_train = log(train$value)

# first difference
log_train_firstDiff = diff(log_train, difference = 1)
plot(log_train_firstDiff, type = "l", main = "first difference")

# second difference
log_train_secDiff = diff(log_train, difference = 2)
plot(log_train_secDiff, type = "l", main = "second difference")
```

```{r check stationarity}
# first difference
#install.packages("tseries")
library(tseries)
adf.test(train_firstDiff)
adf.test(log_train_firstDiff)
```

Time series used is the first difference of the log transformed data.


```{r act and pacf of firstDiff}
acf(log_train_firstDiff)
pacf(log_train_firstDiff)
```

```{r periodogram}
spec <- spec.pgram(log_train_firstDiff, taper = 0, log = "no")
plot(spec$freq, spec$spec, type = "l", xlab = "Frequency", ylab = "Periodogram")

max_index <- which.max(spec$spec)
max_freq <- spec$freq[max_index]

# Calculate the period
period <- 1/max_freq
```

```{r use GridSearch for hyperparameters ARIMA}
searchParamsARIMA <- function(pList, dList, qList, metric, ts){
  bestScore <- 0
  bestParams <- c(0,0,0)
  metric = metric
  for (p in pList){
    for (d in dList){
      for (q in qList){
        params = c(p, d, q)
        model = arima(ts, order = params, include.mean = FALSE, method = "ML")
        # change AIC() for different metrics
        score = metric(model)
        if (score < bestScore) {
          bestScore = score
          bestParams = c(p,d,q)
        }
      }
    }
  }
  msg <- sprintf("Best Params (p, d, q): %d, %d, %d, with score of %0.3f", bestParams[1], bestParams[2], bestParams[3], bestScore)
  print(msg)
}

# test code
# pList = c(0,1,2); dList = c(0,1,2); qList = c(0,1,2)
# metric = AIC
# ts = log_train_firstDiff
# searchParamsARIMA(pList, dList, qList, metric, ts)
```

``` {r search best params}
# params
pList = c(0:2)
dList = c(1)
qList = c(0:2)
m = AIC
ts = log_train_firstDiff
# aic model
searchParamsARIMA(pList, dList, qList, metric = m, ts)
# bic model
m = BIC
searchParamsARIMA(pList, dList, qList, metric = m, ts)
```

```{r SARIMA model}
# searchParamsSARIMA
searchParamsSARIMA <- function(pList, dList, qList, PList, DList, QList, sList, metric, ts){
  bestScore <- 0
  bestParams <- c(0,0,0,0,0,0,0)
  metric = metric
  for (p in pList){
    for (d in dList){
      for (q in qList){
        for (P in PList){
          for (D in DList){
            for (Q in QList){
              for (s in sList){
                params = c(p, d, q)
                seasons = c(P, D, Q)
                periods = s
                sModel = arima(ts, order = params, seasonal = list(order = seasons, period = periods))
                score = metric(sModel)
                if (score < bestScore) {
                  bestScore = score
                  bestParams = c(p,d,q)
                  bestSeasons = c(P, D, Q)
                  bestPeriod = s
                }
              }
            }
          }
        }
      }
    }
  }
  msg <- sprintf("Best Params (p, d, q, P, D, Q, s): %d, %d, %d, %d, %d, %d, %d with score of %0.3f",
                 bestParams[1], bestParams[2], bestParams[3],
                 bestSeasons[1], bestSeasons[2], bestSeasons[3],
                 bestPeriod = s,
                 bestScore)
  print(msg)
}

# test code
# params
pList = c(0:2); dList = c(1); qList = c(0:2)
PList = c(0); DList = c(1); QList = c(0)
sList = c(1)
m = AIC
ts = log_train_firstDiff
# aic model
searchParamsSARIMA(pList, dList, qList, PList, DList, QList, sList, metric = m, ts)
# bic model
m = BIC
searchParamsSARIMA(pList, dList, qList, PList, DList, QList, sList, metric = m, ts)
```

```{r build model, evaluate model appropriateness}
bestModel = arima(log_train_firstDiff, order = c(0,1,1), include.mean = FALSE)

acf(bestModel$residual ,col='red')
pacf(bestModel$residual ,col='red')
tsdiag(bestModel)
hist(bestModel$residual,col='darkorange')
qqnorm(bestModel$residual ,col='red')

```

```{r forecasting}
# install.packages("forecast")
library(forecast)
forecasts = forecast(bestModel, h = 5)
plot(forecasts)
```
```{r plot into original timeseries}
x1 = fertilityRate$year
y1 = fertilityRate$value

# forecast
fore0 = exp(tail(log_train_firstDiff, 1) + cumsum(forecasts$mean))
y2 = c(y1[1:length(train$value)], fore0)

fore97.5 = exp(tail(log_train_firstDiff, 1) + cumsum(forecasts$upper[, c(2)]))
fore2.5 = exp(tail(log_train_firstDiff, 1) + cumsum(forecasts$lower[, c(2)]))
y3 = c(y1[1:length(train$value)], fore97.5)
y4 = c(y1[1:length(train$value)], fore2.5)

fore90 = exp(tail(log_train_firstDiff, 1) + cumsum(forecasts$upper[, c(1)]))
fore10 = exp(tail(log_train_firstDiff, 1) + cumsum(forecasts$lower[, c(1)]))
y5 = c(y1[1:length(train$value)], fore90)
y6 = c(y1[1:length(train$value)], fore10)

# plot
plot(x1, y2, ylim = c(0,max(y1)), type = "l", col = "red",
     main = "Actual vs Forecasted",
     xlab = "Fertility Rate",
     ylab = "Year")
lines(x1, y3, type = "l", col = "gold")
lines(x1, y4, type = "l", col = "gold")
lines(x1, y5, type = "l", col = "orange")
lines(x1, y6, type = "l", col = "orange")
lines(x1, y1, type = "l", col = "blue")

legend(x = "topright",
       inset = 0.05,
       title = "Legend",
       legend = c("Actual", "Forecast", "80% C.I.", "95% C.I."),
       fill = c("blue", "red", "orange", "gold"))
```
